{"name": "test_login_params[data_for_login1]", "status": "passed", "attachments": [{"name": "log", "source": "e0c52c68-cb5d-4720-9e16-eeda90f0029b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('adelukesh1@gmail.com', '12345', 'Fail')"}], "start": 1751784447850, "stop": 1751784451971, "uuid": "33f028b8-4ade-4f54-b766-f4e3a3d9ed3e", "historyId": "4de2338e3b208b25a3a2b07a9b7ad841", "testCaseId": "5fe6fe3249a01c883d8efece63f2c386", "fullName": "test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "18356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_params"}]}