{"name": "test_login_params[data_for_login4]", "status": "passed", "attachments": [{"name": "log", "source": "0c03aabc-5c60-404c-afcb-df0dbe2099bb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('', '', 'Fail')"}], "start": 1743801405521, "stop": 1743801408169, "uuid": "305a1f21-e839-4587-804d-9d144523a220", "historyId": "5cc684edec223d1983922da115a14b9d", "testCaseId": "5fe6fe3249a01c883d8efece63f2c386", "fullName": "test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_params"}]}