{"name": "test_login_params[data_for_login1]", "status": "passed", "attachments": [{"name": "log", "source": "ac524a77-a0cd-4e05-b12a-c4979f1e4de1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('adelukesh1@gmail.com', '12345', 'Fail')"}], "start": 1744778511517, "stop": 1744778514157, "uuid": "e5578898-a7db-4f78-a6a8-e1c04177b220", "historyId": "4de2338e3b208b25a3a2b07a9b7ad841", "testCaseId": "5fe6fe3249a01c883d8efece63f2c386", "fullName": "test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "4492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_params"}]}