{"uuid": "ee8ff959-ab18-4396-958f-38ab03482d6d", "children": ["a1efeaec-1c0f-4a51-9c35-dbf3c90cb3c3"], "befores": [{"name": "setup", "status": "passed", "start": 1750018148207, "stop": 1750018149249}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\testCases\\conftest.py\", line 74, in setup\n    driver.quit()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 157, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 142, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Program Files\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1750018152683, "stop": 1750018154769}], "start": 1750018148207, "stop": 1750018154769}