{"name": "test_login_params[data_for_login3]", "status": "passed", "attachments": [{"name": "log", "source": "3d7d0d0a-1755-4165-9f05-21fc61da0fdf-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('adelukesh24@gmail.com', '54851', 'Fail')"}], "start": 1745752039845, "stop": 1745752042752, "uuid": "22a988fb-f4f8-4f45-8bae-3c9bd0d52da4", "historyId": "d86d1153d36b45d62101e56b53503bb5", "testCaseId": "47f970e602e4eefb1a3e5455dd555a36", "fullName": "testCases.test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "17944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login_params"}]}