{"name": "test_login_functionality_001", "status": "passed", "attachments": [{"name": "log", "source": "94e91d06-f07b-459c-8ad2-fc393f45e0ce-attachment.txt", "type": "text/plain"}], "start": 1747037067815, "stop": 1747037073227, "uuid": "94090879-88b7-426b-92b1-4e55c900aa55", "historyId": "6ed91ba5a6315ed24f37908113426b3c", "testCaseId": "6ed91ba5a6315ed24f37908113426b3c", "fullName": "testCases.test_login.Test_002_Login_Functionality#test_login_functionality_001", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_002_Login_Functionality"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "2992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}]}