[32mINFO    [0m Test_005_Search_Functionality:test_search.py:22 **************** Test Search Functionality 001 Started ******************
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:24 Navigating to the URL
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:27 Searching iMac
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:29 Clicking on search button
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:31 *********** Verifying Test Search functionality 001 ************
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:34 iMac
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:36 ********** Test Search Functionality 001 is Passed ***********
[32mINFO    [0m Test_005_Search_Functionality:test_search.py:41 ***************** End Of Test Search Functionality 001 ******************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BE0B7B06B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c4c312f3ae9d8a488feffdfe66f7c21e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BE0B63F9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c4c312f3ae9d8a488feffdfe66f7c21e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BE0BB7C050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c4c312f3ae9d8a488feffdfe66f7c21e