{"name": "test_login_functionality_001", "status": "passed", "attachments": [{"name": "log", "source": "cc84a68b-4675-47bd-914b-370a9e760381-attachment.txt", "type": "text/plain"}], "start": 1746997836934, "stop": 1746997843115, "uuid": "1cc8ecee-e606-4f88-95ef-f7beed4570cd", "historyId": "6ed91ba5a6315ed24f37908113426b3c", "testCaseId": "6ed91ba5a6315ed24f37908113426b3c", "fullName": "testCases.test_login.Test_002_Login_Functionality#test_login_functionality_001", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_002_Login_Functionality"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "28956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login"}]}