{"name": "test_login_params[data_for_login1]", "status": "passed", "attachments": [{"name": "log", "source": "9785b024-3f8b-4914-be98-98460f7f7491-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('adelukesh1@gmail.com', '12345', 'Fail')"}], "start": 1743767322511, "stop": 1743767325929, "uuid": "1ff2c83c-1d6d-4c7c-b52e-a2c1d609e03b", "historyId": "4de2338e3b208b25a3a2b07a9b7ad841", "testCaseId": "5fe6fe3249a01c883d8efece63f2c386", "fullName": "test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "10384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_params"}]}