{"name": "test_login_params[data_for_login3]", "status": "passed", "attachments": [{"name": "log", "source": "f92a743f-5d8b-41f8-a388-cc6c0cf25d7c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data_for_login", "value": "('adelukesh24@gmail.com', '54851', 'Fail')"}], "start": 1743434333094, "stop": 1743434338395, "uuid": "b413476c-42a0-4028-a200-e839d1bc882c", "historyId": "d86d1153d36b45d62101e56b53503bb5", "testCaseId": "47f970e602e4eefb1a3e5455dd555a36", "fullName": "testCases.test_login_params.TestLoginParams#test_login_params", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login_params"}, {"name": "subSuite", "value": "TestLoginParams"}, {"name": "host", "value": "lukesh"}, {"name": "thread", "value": "14844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login_params"}]}