[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:71 ************ Test Forgot Password 003 Start ************
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:73 Navigating to the url
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:76 clicking on my account
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:78 clicking on login link
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:81 clicking on forgot password link
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:82 ************ Verifying Test Forgot Password 003 ************
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:85 E-Mail Address
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:87 *********** Test Forgot Password 003 Passed *************
[32mINFO    [0m Test_004_Forgot_Password:test_forgot_password.py:93 ************** End of Test Forgot Password 003 ********************
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018FF759E990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49945c4391407410b03a115e5fce8d7c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018FF759F610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49945c4391407410b03a115e5fce8d7c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018FF762CD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/49945c4391407410b03a115e5fce8d7c