{"uuid": "ab477ed1-4f45-4d52-8c37-e70a05c5d0a7", "children": ["e7987b2b-f5e2-4d26-b9c9-bc912ecd3a0c"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Drivers\\chromedriver.exe unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\testCases\\conftest.py\", line 17, in setup\n    driver = webdriver.Chrome(service=serv_obj, options=options)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 55, in __init__\n    self.service.start()\n    ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 113, in start\n    self.assert_process_still_running()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1743158330855, "stop": 1743158332890}], "start": 1743158330855, "stop": 1743158332922}