{"uuid": "dd7306ce-cec7-4aec-9d7a-fe32ad687ab5", "children": ["26b1f37c-e3fe-4f7b-9e66-1abfd82f5690"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Drivers\\chromedriver.exe unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\testCases\\conftest.py\", line 17, in setup\n    driver = webdriver.Chrome(service=serv_obj, options=options)\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 55, in __init__\n    self.service.start()\n    ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 113, in start\n    self.assert_process_still_running()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\lukesh ade\\Credence Testing 8\\Credence Testing 21 new batch\\AutomationProject\\TutorialsNinjaWebApplication\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1743158328784, "stop": 1743158330830}], "start": 1743158328784, "stop": 1743158330857}